FROM python:3.12-slim

WORKDIR /app

# Copy file requirements trước để tạn dụng cache
COPY requirements.txt .

# Cài dependency
RUN pip install --no-cache-dir -r requirements.txt

# Copy phần còn lại (code, pytest.ini, ...)
COPY . .

# Default CMD
# CMD ["pytest", "-q", "--disable-warnings", "--maxfail=1"]
