MAKE_DROPDOWN = 'xpath:(//div[@class="rc-virtual-list"])[1]//div[@class="ant-select-item-option-content"]'
FUNCTION_DROPDOWN = 'xpath:(//div[@class="rc-virtual-list"])[2]//div[@class="ant-select-item-option-content"]'
SEARCH_BTN = 'xpath://button[contains(., "Search")]'
PRODUCTION_DB = 'text:Production Database'
HANDLE_MAKE = 'xpath://div[@class="subItem" and contains(text(), "Handle Make")]'
MAKE_BOX = 'id:make'
FUNCTION_BOX = 'id:function'
CLONE_VERSION_BTN_PRO_DB = 'xpath:(//button[@type="button" and contains(., "Clone Version")])[1]'
CLONE_VERSION_BTN_DEV_DB = 'xpath:(//button[@type="button" and contains(., "Clone Version")])[2]'
IMPORT_EXCEL_BTN_PRO_DB = 'xpath:(//button[@type="button" and contains(., "Import To Create")])[1]'
IMPORT_EXCEL_BTN_DEV_DB = 'xpath:(//button[@type="button" and contains(., "Import To Create")])[2]'
CANCEL_BTN = 'xpath://button[@type="button" and contains(., "Cancel")]'
CONFIRM_BTN = 'xpath://button[@type="submit" and contains(., "Confirm")]'
X_ICON = 'xpath://span[@class="anticon anticon-close ant-modal-close-icon"]'
VERSIONS_RDBTN = 'xpath://input[@class="ant-radio-input"]'
VERSIONS_TEXT = 'xpath://input[@class="ant-radio-input"]/../following-sibling::span[1]'
SUCCESSFUL_MSG = 'xpath://div[@class="ant-message-custom-content ant-message-success"]'
HEADERS_PRO_DB = 'xpath:(//div[@class="ant-table-container"])[1]//th[@class="ant-table-cell"]'
HEADERS_DEV_DB = 'xpath:(//div[@class="ant-table-container"])[2]//th[@class="ant-table-cell"]'
ACTION_COLUMN_PRO_DB = 'xpath:(//div[@class="ant-table-container"])[1]//th[contains(@class, "ant-table-cell-fix-right-first")]'
ACTION_COLUMN_DEV_DB = 'xpath:(//div[@class="ant-table-container"])[2]//th[contains(@class, "ant-table-cell-fix-right-first")]'
ACTION_ITEMS = 'xpath://li[@role="menuitem"]'
DELETE_ACTION = 'xpath://li[@role="menuitem"]//span[contains(text(),"Delete")]'
EDIT_ACTION = 'xpath://li[@role="menuitem"]//a[contains(text(),"Edit")]'
RELEASE_ACTION = 'xpath://li[@role="menuitem"]//a[contains(text(),"Release")]'
CELLS_PRO_DB = 'xpath:(//div[@class="ant-table-container"])[1]//td[@class="ant-table-cell"]'
CELLS_DEV_DB = 'xpath:(//div[@class="ant-table-container"])[2]//td[@class="ant-table-cell"]'
DRAFT_STATUS_PRO_DB = 'xpath:(//div[@class="ant-table-container"])[1]//td[@class="ant-table-cell"]//span[contains(., "DRAFT")]'
DRAFT_STATUS_DEV_DB = 'xpath:(//div[@class="ant-table-container"])[2]//td[@class="ant-table-cell"]//span[contains(., "DRAFT")]'
ARROWS_DOWN_ICON_PRO_DB = 'xpath:(//div[@class="ant-table-container"])[1]//span[@class="anticon anticon-down"]'
ARROWS_DOWN_ICON_DEV_DB = 'xpath:(//div[@class="ant-table-container"])[2]//span[@class="anticon anticon-down"]'
LOG_CHANGE_DETAIL_FIELDS = 'xpath://div[@class="ant-drawer-body"]//p'
LOG_CHANGE_TITLE = 'xpath://div[@class="ant-drawer-body"]//h4'
LOG_CHANGE_CONTENTS = 'xpath://div[@class="ant-drawer-body"]//h4/following-sibling::div[1]'
DRAFT_VIEWS_BTN_PRO_DB = 'xpath:(//div[@class="ant-table-container"])[1]//tr[2]//button[@type="button" and contains(., "View")]'
DRAFT_VIEWS_BTN_DEV_DB = 'xpath:(//div[@class="ant-table-container"])[2]//tr[2]//button[@type="button" and contains(., "View")]'
CLOSE_SECTION_ICON = 'xpath://div[@class="ant-drawer-content-wrapper"]//button[@aria-label="Close"]'
CANCEL_CONFIRM_BTN = 'xpath://div[@class="ant-popconfirm-buttons"]//button[contains(., "Cancel")]'
OK_CONFIRM_BTN = 'xpath://div[@class="ant-popconfirm-buttons"]//button[contains(., "OK")]'
DELETE_BTN = 'xpath://li[@role="menuitem"]//span[contains(text(), "Delete")]'
INPUT_NOTES_BOX = 'xpath://div[@class="ant-form-item-control-input-content"]//textarea'
RD_NOTES_BOX = 'xpath://textarea[@id="rad_note"]'
RELEASE_NOTES_BOX = 'xpath://textarea[@id="release_note"]'
LIB_LOG_BOX = 'xpath://textarea[@id="lib_log"]'
SAVE_ACTION_BTN = 'xpath://a[normalize-space()="Save"]'
CANCEL_ACTION_BTN = 'xpath://a[normalize-space()="Cancel"]'
RD_NOTE_RELEASE = 'placeholder:R&D Note placeholder'
RELEASE_NOTE_RELEASE = 'placeholder:Release Note placeholder'
LIB_LOG_RELEASE = 'placeholder:Lib Log placeholder'
COMMON_VER_DROPDOWN = 'xpath://label[@for="commonVersionList"]/parent::div/following-sibling::div[1]//div[@class="ant-select-selector"]'
UPLOAD_BTN = 'xpath://button[contains(.,"Upload")]'
REMOVE_FILE_UPLOAD_ICON = 'xpath://span[@class="anticon anticon-delete"]'
COMMON_VERS_LIST = 'xpath://div[@id="commonVersionList_list"]/following-sibling::div[contains(@class,"rc-virtual-list")]//div[@class="ant-select-item-option-content"]'
DOWNLOAD_EXCEL_BTN_PRO_DB = 'xpath:(//a[normalize-space()="Download Excel"])[1]'
ICONS_NOTIFICATION = 'xpath://div[@class="notification-container"]//a[@class="cursor-pointer"]'
NOTIFICATION_TITLES = 'xpath://div[@class="notification-title"]'
NOTIFICATION_CONTENTS = 'xpath://div[@class="notification-message"]'
LOGOUT_BTN = 'xpath://p[normalize-space()="Log Out"]'
BELL_ICON= 'xpath:(//div[@class="notification-container"]//a[@class="cursor-pointer"])[2]'
ERROR_ICON= 'xpath:(//div[@class="notification-container"]//a[@class="cursor-pointer"])[1]'
BELL_NUMBER_UNIT = 'xpath://span[@class="ant-scroll-number-only-unit current"]'
DB_TYPE_DROPDOWN = 'xpath://label[@for="form_in_modal_databaseType"]/../following-sibling::div[1]//div[@class="ant-select-selector"]'
DB_TYPE_ITEMS = 'xpath://div[@id="form_in_modal_databaseType_list"]/following-sibling::div[1]//div[@class="ant-select-item-option-content"]'
FROM_VERSION_DROPDOWN = 'xpath://label[@for="form_in_modal_fromVersion"]/../following-sibling::div[1]//div[@class="ant-select-selector"]'
FROM_VERSION_ITEMS = 'xpath://div[@id="form_in_modal_fromVersion_list"]/following-sibling::div[1]//div[@class="ant-select-item-option-content"]'
FORM_ERROR_MSG = 'xpath://div[@class="ant-form-item-explain-error"]'